apiVersion: apps/v1
kind: Deployment
metadata:
  name: testhttp-app
  labels:
    app: testhttp-application
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: testhttp
  template:
    metadata:
      labels:
        app: testhttp
    spec:
      containers:
        - name: go-testhttp
          image: dark705/go-testhttp
          ports:
            - name: http
              containerPort: 8000
            - name: prometheus-http
              containerPort: 9000
          startupProbe:
            initialDelaySeconds: 5
            httpGet:
              port: 8000
              path: /kuber/startup
            periodSeconds: 1
          livenessProbe:
            httpGet:
              port: 8000
              path: /kuber/live
            periodSeconds: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              port: 8000
              path: /kuber/ready
            periodSeconds: 1
            failureThreshold: 1
          env:
            - name: KUBER_PROBE_START_UP_SECONDS
              value: "0"
            - name: KUBER_PROBE_PROBABILITY_LIVE
              value: "100"
            - name: KUBER_PROBE_PROBABILITY_READY
              value: "100"
